### ISSUE TITLE
Issue running tf-recurrent-sin-5.py

### ISSUE THREAD

**Issue by robotdude17** [sunsided/tensorflow-lstm-sin#1]
I've tried to run tf-recurrent-sin-5.py and ran into the following error:

python tf-recurrent-sin-5.py
Traceback (most recent call last):
  File "tf-recurrent-sin-5.py", line 47, in <module>
    outputs, states = tf.nn.dynamic_rnn(stacked_lstm, x, dtype=tf.float32, time_major=False)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 574, in dynamic_rnn
    dtype=dtype)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 737, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2770, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2599, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2549, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 722, in _time_step
    (output, new_state) = call_cell()
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 708, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 916, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 383, in call
    concat = _linear([inputs, h], 4 * self._num_units, True)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1017, in _linear
    initializer=kernel_initializer)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1405, in wrapped_custom_getter
    *args, **kwargs)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/.../anaconda3/envs/time-series-1/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 669, in _get_single_variable
    found_var.get_shape()))
ValueError: Trying to share variable rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel, but specified shape (64, 128) and found shape (33, 128).

I'm using python 3.5. and tensorflow-gpu 1.2.0.

The following scripts are running on my system:

tf-recurrent-sin.py to tf-recurrent-sin-4.py

Could you please let me know what went wrong?

Thanks a lot!

**Comment by robotdude17** [comment]
Update: It's probably something to do with the version of tensorflow.
On my system the script tf-recurrent-sin-5.py runs using tensorflow-gpu 1.0 but not using tensorflow-gpu 1.2.0.
Best regards.

**Comment by kissste** [comment]
The same problem here, running python 3.5 with tensorflow_gpu-1.3.0

ValueError: Trying to share variable rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel, but specified shape (64, 128) and found shape (33, 128).

**Comment by sunsided** [comment]
Hey guys, sorry for the delay. There's a bug in the code for the multi-layer LSTM creation. The way it is currently set up, the same layer will be reused `n_layers` times, rather than creating `n_layers` separate layers. The issue is described [here](https://stackoverflow.com/questions/44615147/valueerror-trying-to-share-variable-rnn-multi-rnn-cell-cell-0-basic-lstm-cell-k) on StackOverflow, for example.

I'll merge a fix, this should also address #2.
